# Setup
title:               Linux-Wpan
tagline:             'A Jekyll theme'
description:         'Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://linux-wpan.org/website-test.github.io/index.html
baseurl:             'http://linux-wpan.org/website-test.github.io'
paginate:            12

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             0.8.0
